# Generated by Django 4.1.8 on 2023-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0002_bankaccount_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementline",
            name="amount",
            field=models.FloatField(),
        ),
    ]
