# Generated by Django 4.1.8 on 2023-05-07 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0003_alter_statementline_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name_plural": "Subcategories"},
        ),
    ]
