# Generated by Django 4.1.8 on 2023-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0004_alter_category_options_alter_subcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementline",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
