# Generated by Django 4.1.13 on 2025-07-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_ingestion", "0005_alter_statementline_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementline",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accountstatement",
            name="statement_type",
            field=models.CharField(
                choices=[
                    ("BS", "Bank Statement"),
                    ("CA", "Card Receipts"),
                    ("CR", "Credit"),
                    ("DB", "Debit"),
                    ("OT", "Other"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="statementline",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("DD", "Direct Debit"),
                    ("CB", "Bank Card"),
                    ("CH", "Cheque"),
                    ("CA", "Cash"),
                    ("RE", "Refund"),
                    ("IN", "Interest"),
                    ("TR", "Transfer"),
                    ("OT", "Other"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ShareRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_ingestion.subcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "label", "sub_category")},
            },
        ),
    ]
