# Generated by Django 4.1.13 on 2025-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0006_statementline_is_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharerule",
            name="always_shared",
            field=models.BooleanField(default=True),
        ),
    ]
