# Generated by Django 4.1.13 on 2025-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_ingestion", "0007_sharerule_always_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharerule",
            name="always_shared",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="statementline",
            name="is_shared",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
